spring:
  profiles:
   active:
   - dev
---
server:
  port: 9003
spring:
  profiles: dev   #开发环境
  application:
    name: microservice-config-eureka9003
 
eureka: 
  #server:
    #enable-self-preservation: false   #关闭eureka自我保护机制  #不推荐
  instance:
    hostname: eureka9003.com  #eureka服务端的实例名称
  client: 
    register-with-eureka: false  #false表示自己不向注册中心注册自己
    fetch-registry: false  #false表示自己自己就是注册中心，不需要去检索服务，职责是维护服务实例
    service-url:                                                                                                                                 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/